### PR TITLE
Fixed missing `tf_predictions` and `save_directory` variables.  Split tf_ and pt_  a bit better.  Added .gitignore to ignore the saved model paths.

### PR DESCRIPTION
**Pull request by cfregly**
@philschmid

### CODE REVIEW

**Comment by LysandreJik** [comment]
Hi @cfregly, thanks for opening a PR!

The notebooks were not synchronized to the latest `master` updates of `transformers`, which led to these errors. I'm bringing all the notebooks up to speed with `master` in the following PR: https://github.com/huggingface/notebooks/pull/118

Could you let me know if that works for you? There won't be the changes to the `save_directory` and the split between `tf_` and `pt_`. If you're feeling strongly about these changes, could you apply them to this file? https://github.com/huggingface/transformers/blob/master/docs/source/quicktour.rst

I'll then re-generate the notebooks so that they contain the changes. Let me know!

**Comment by cfregly** [comment]
@LysandreJik Thanks for the quick response.

the code in the .rst looks good, although I don’t see the save_directory variable being defined, but maybe I’m missing something.

Summary:  As long as the generated code runs without error, I’m ok.

Actually, can you add the commented-out pip install dependencies from the top of my PR?  Makes things a bit more clear.

thanks!!

**Comment by LysandreJik** [comment]
Yes, the `save_directory` variable is not defined as mentioned in my message above; I personally think it's not an issue as it's pretty explicit, but if you feel strongly about it please do apply your changes to https://github.com/huggingface/transformers/blob/master/docs/source/quicktour.rst and I'll be happy to merge it and update the notebooks.

Please do note that the cells right after the model saving won't necessarily work out of the box as it is indicated in the notebook that some cells are only shown if the user would like to load a TF model in a PT model, or vice-versa, which is not the case if you're following the notebook from start to finish.

I confirm all other cells run to completion.

**Comment by cfregly** [comment]
Gotcha.

I think it’s important for this notebook to run to completion without error.  Seems like a better experience for the end user.

I’ll apply all of my changes to the .rst and we can go from there.

Thanks so much!

**Comment by LysandreJik** [comment]
That sounds good, will keep an eye out for the PR. Thanks, @cfregly!

**Comment by cfregly** [comment]
@LysandreJik 

Ok, i've created a PR to the transformers/ repo:  https://github.com/huggingface/transformers/pull/14529

I'll keep an eye on that PR and delete this PR in the next couple days.

**Comment by LysandreJik** [comment]
Merged your PR, updated it in https://github.com/huggingface/transformers/pull/14533 and applied the changes in https://github.com/huggingface/notebooks/pull/118.

I had to do another follow up PR here https://github.com/huggingface/transformers/pull/14534 and applied the changes in https://github.com/huggingface/notebooks/pull/119

**Pull request closed without merging**
