### PR TITLE
Add telemetry to (almost) all notebooks

### PR DESCRIPTION
**Pull request by Rocketknight1**
This PR adds telemetry to all the notebooks, along with an apologetic explanation. I'm still making some fixes, so this is a draft for now, don't bother with reviewing it yet!

### CODE REVIEW

**Comment by Rocketknight1** [comment]
`git` seems to have parsed this PR as much bigger changes than it actually is and I don't understand why! If you look in `ReviewNB` you can see the text removed and text inserted is exactly the same. Possibly some of the notebooks were produced with an older version of Jupyter, and so when I opened and saved them it rewrote metadata in almost every cell.

**Comment by Rocketknight1** [comment]
This should be ready to go except for the giant diffs - trying to figure that one out now.

**Review by sgugger — APPROVED** [review]
Thanks for adding this!

**Comment by Rocketknight1** [comment]
I double-checked everything and the diffs show no actual changes to the notebook content. I can't get rid of the massive diffs, so I'm just going to merge it as-is and assume it'll be fine!

**Pull request merged**
