### PR TITLE
add pad_to_multiple_of to data_collator

### PR DESCRIPTION
**Pull request by nbroad1881**
I've never made a pull request for .ipynb files before.  It seems impossible to tell what the changes are because it says every single line has been changed... Is there a better way of making changes? 

@patrickvonplaten, I believe you uploaded this originally

 I tested my new version and it works just fine. https://colab.research.google.com/drive/1CgGHSP0z1PwJURgmirds736dFWoAm-b_?usp=sharing

# Summary of changes:

## Add pad_to_multiple_of

Previously, the data_collator calls would fail because `pad_to_multiple_of` was included as an argument in the training loop but not in the  `__call__` function definition

Old
```python
@flax.struct.dataclass
class FlaxDataCollatorForMaskedLanguageModeling:
    mlm_probability: float = 0.15

    def __call__(self, examples, tokenizer):
        batch = tokenizer.pad(examples, return_tensors="np")
```

New
```python
@flax.struct.dataclass
class FlaxDataCollatorForMaskedLanguageModeling:
    mlm_probability: float = 0.15

    def __call__(self, examples, tokenizer, pad_to_multiple_of=16):
        batch = tokenizer.pad(examples, return_tensors="np", pad_to_multiple_of=pad_to_multiple_of)
```

## Delete unnecessary imports

Old  
```python
from tokenizers import trainers, Tokenizer, normalizers, ByteLevelBPETokenizer
```   
New   
```python
from tokenizers import ByteLevelBPETokenizer 
```

## MInor spelling fix to explanation

Old  
>"File deplicated" column on the official OSCAR website.  

New  
> "deduplicated" column on the official OSCAR website.

## Fix sentence to match code behavior and add clarity.

Old  

>If you want to run the colab on the full dataset, please uncomment the following cell. In this case the notebook will run for ca. 12 hours until loss convergence and give a final accuracy of around 50%.

New  

>If you want to run the colab on the full dataset, please comment the following cell. Using the full dataset, the notebook will run for ca. 12 hours until loss convergence and give a final accuracy of around 50%.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Sorry for being so late here! I'll take a look on Monday

**Comment by patrickvonplaten** [comment]
I'll check out your google colab and if looks good, I think we can merge the PR or save your google colab in github :-)

**Comment by nbroad1881** [comment]
Thanks Patrick! If you think it's good, I could hit the merge button myself for the first time as a Hugging Face employee :)

**Comment by patrickvonplaten** [comment]
Hey @nbroad1881, 

Feel free to merge the PR - I trust you on this :-) Thanks for the in-detail explanation

**Review by patrickvonplaten — APPROVED** [review]

**Pull request merged**
