### PR TITLE
Add image-guided object detection example to the OWL-ViT demo

### PR DESCRIPTION
**Pull request by alaradirik**
# What does this PR do?
Adds one-shot / image-guided object detection example to the OWL-ViT demo.

Image-guided object detection support will be added shortly with this [PR](https://github.com/huggingface/transformers/pull/18891).

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
I'm not sure, I'll find time soon to review this - @NielsRogge do you maybe have some time :sweat_smile:

**Comment by sayakpaul** [comment]
I can take this up for review. Let me know.

**Comment by alaradirik** [comment]
<p>Moving them to another cell with an optional flag</p>

---

 <a href='https://app.reviewnb.com/huggingface/notebooks/pull/256/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by alaradirik** [comment]
> I can take this up for review. Let me know.

Thank you @sayakpaul, @NielsRogge did a review.

**Comment by lipido** [comment]
Hi!

I was trying to run the Google Colab without doing any modification, and all runs fine. However, the cats are both in one bounding box. I tried to play with thresholds, but I was unable to reproduce the expected results (only two bounding boxes)

twocatsOneBox

**Pull request merged**
