### PR TITLE
Contribute working version of Stable Diffusion on Mac OSX M3 Max

### PR DESCRIPTION
**Pull request by chrismattmann**
This PR contributes a working version of Stable Diffusion notebook for Mac OS X M3 Max.

Fixes #9967 Tried to run diffusers/stable_diffusion.ipynb on Mac M3 and ran into errors

## Who can review?

@pcuenca @sayakpaul

### CODE REVIEW

**Comment by pcuenca** [comment]
Thank you @chrismattmann! Did you have to make any compatibility changes, other than changing the compute device to `mps` (and ignoring nvidia-smi)? If so, perhaps it could be more interesting to bring the device selection (`cuda` or `mps`) to [the original notebook](https://github.com/huggingface/notebooks/blob/main/diffusers/stable_diffusion.ipynb) so any future updates are easier to maintain.

**Comment by chrismattmann** [comment]
@pcuenca good point, I think that was the only changes was device selection. I suppose I could parameterize it. I will take a look at doing that this weekend and send an update!

**Comment by chrismattmann** [comment]
OK @pcuenca updated in https://github.com/huggingface/notebooks/pull/533/commits/a52e0e5ea1e8b87e782018bb52a46d7cae760306 please review

**Comment by sayakpaul** [comment]
I will let @pcuenca to review and merge :)

**Comment by chrismattmann** [comment]
> I will let @pcuenca to review and merge :)

Thank you! @pcuenca can you please take a look? Thanks @sayakpaul !

**Comment by sayakpaul** [comment]
Please allow till this week to review. Feel free to re-ping after that :-)

**Comment by chrismattmann** [comment]
@pcuenca @sayakpaul sorry to bother you but you mentioned to re-ping in a week, so I'm doing that. Thanks!

**Review by pcuenca — COMMENTED** [review]
Hello @chrismattmann! Thanks for the ping, and sorry for being slow to review 🙏 

The PR is looking good, I just have a few minor comments:

- Instead of using `platform`, I would show the use of `nvidia-smi` if this condition succeeds:

```py
if torch.cuda.is_available():
    # Shows the nVidia GPUs, if this system has any
    !nvidia-smi
```

- Similarly, I would verify that the `mps` device is indeed available. Note that the platform being `Darwin` does **not** guarantee the existence of such device. So I would use something like this:

```py
    if torch.cuda.is_available():
        device=torch.device("cuda")
    elif torch.backends.mps.is_available():
        device=torch.device("mps")
```

With this change, you no longer need the `isosx` variable and can move tensors and pipelines `.to(device)` everywhere.

- You can also use the `device` variable, as used above, instead of defining another one (`generator_type`) for the generator. The following should work:

```py
generator = torch.Generator(device).manual_seed(1024)
```

Thanks a lot for your patience, I believe we are very close to finally merging this!

**Comment by chrismattmann** [comment]
thanks @pcuenca I will make these updates and contribute an update this week!

**Comment by pcuenca** [comment]
Thanks a lot @chrismattmann, feel free to ping me when you do 🙌

**Comment by chrismattmann** [comment]
Dear @pcuenca I've gone ahead and addressed the comments. Please review and merge! :)

**Review by pcuenca — APPROVED** [review]
Thanks a lot, @chrismattmann! 🙌 🔥

**Comment by chrismattmann** [comment]
Thank you @pcuenca ! appreciate you!

**Comment by chrismattmann** [comment]
Thank you and this closes #9967

**Pull request merged**
