### PR TITLE
Update tasks reference

### PR DESCRIPTION
**Pull request by emmanuel-ferdman**
# PR Summary
Small PR - Updates the location of `all_tasks.txt`.

### CODE REVIEW

**Review by svlandeg — APPROVED** [review]
Edit is correct - the new link works, while the old one 404's.

**Comment by svlandeg** [comment]
I'm not a maintainer of this repo 😉  I just came across this PR because I noticed the same issue and didn't want to submit a duplicate PR 😉

**Comment by emmanuel-ferdman** [comment]
@stevhliu please review this small PR when you get the chance 🙌

**Review by stevhliu — APPROVED** [review]
Thanks for updating the link!

**Pull request merged**
