### PR TITLE
demo image similarity with `AutoModel`, `datasets`, and more 

### PR DESCRIPTION
**Pull request by sayakpaul**
This PR adds a notebook that shows how to build an image similarity system (near duplicate system as such) using locality-sensitive hashing. We use various tools from our ecosystem for this: `AutoModel`, `datasets`, etc. 

## TODOs

- [x] Complete writing rest of the sections
- [x] Add a Gradio demo 
- [x] Add some call for action in the conclusion 

Colab Notebook: https://colab.research.google.com/github/sayakpaul/notebooks/blob/feat/image-sim/examples/image_similarity.ipynb

### CODE REVIEW

**Comment by sayakpaul** [comment]
Folks, this PR is now ready to be reviewed. Some things to note:

* I wanted to show the readers how the runtime could be optimized (for CPUs) instead of just telling them to use ONNX. I have left comments in the respective sections. Surprisingly, I didn't see any speedup when using ONNX. Could be because of the NCHW memory layout. Have you experienced this behavior before? 

  For now, I have kept the sections for review purposes. But will remove. 
* @freddyaboulton once the initial reviews are in, let's work together to include a Gradio demo (and host a Space)? Cc: @abidlabs

**Review by osanseviero — COMMENTED** [review]
This is really outside my area of expertise, so I would also suggest to get some feedback from @lhoestq from the datasets side

* Can we use https://huggingface.co/docs/datasets/faiss_es here maybe?
* I feel the jump to the hash stuff is somewhat complicated. Maybe before doing that we could do a simple example of using the full embedding to do search with a small subset of the dataset, then we explain it's slow, and then we do the hash stuff. That way the people can do some cool thing first and then optimize it.

**Comment by lhoestq** [comment]
> Can we use https://huggingface.co/docs/datasets/faiss_es here maybe?

Yea you could use FAISS integration with `datasets` if you don't want to show how to code an LSH search (or is it the goal of your blog post ?)

**Comment by sayakpaul** [comment]
<p>Pt 1: Done</p><p> </p><p>Pt 2: Added it after loading of the model. Thought it is more coherent to follow. </p><p> </p><p>Pt 3: Fixed.</p>

---

 <a href='https://app.reviewnb.com/huggingface/notebooks/pull/270/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sayakpaul** [comment]
<p>It came up due to Black formatting :D </p>

---

 <a href='https://app.reviewnb.com/huggingface/notebooks/pull/270/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sayakpaul** [comment]
<p>Reworded to discard the unnecessary information. </p>

---

 <a href='https://app.reviewnb.com/huggingface/notebooks/pull/270/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sayakpaul** [comment]
<p>Same as above :D </p>

---

 <a href='https://app.reviewnb.com/huggingface/notebooks/pull/270/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sayakpaul** [comment]
> Can we use https://huggingface.co/docs/datasets/faiss_es here maybe?

@osanseviero @lhoestq Really cool stuff. How about we divide the tutorial into two parts? Pt. 1 covers the current outline and Pt. 2 will focus on `faiss_es` and we link it from Pt. 1?

> I feel the jump to the hash stuff is somewhat complicated. Maybe before doing that we could do a simple example of using the full embedding to do search with a small subset of the dataset, then we explain it's slow, and then we do the hash stuff. That way the people can do some cool thing first and then optimize it.

Onboarded. Will change accordingly but let's discuss the above point first.

**Comment by lhoestq** [comment]
> @osanseviero @lhoestq Really cool stuff. How about we divide the tutorial into two parts? Pt. 1 covers the current outline and Pt. 2 will focus on faiss_es and we link it from Pt. 1? I wrote this [notebook](https://colab.research.google.com/gist/sayakpaul/89dbbbfb646b954f4c790393daec0a4e/scratchpad.ipynb) that shows the use of our FAISS utilities for finding similar images as well.

Keeping the current outline and add links to this documentation is also fine IMO, as you want

**Comment by sayakpaul** [comment]
> Keeping the current outline and add links to this documentation and the notebook is also fine IMO, as you want

I'd be down to that. I can polish the notebook and link it from the current one alongside the documentation. 

Later in [the blog post](https://github.com/huggingface/blog/pull/663), we will touch on these points at a high level.

**Comment by sayakpaul** [comment]
<p>WDYT about this one?</p><p> </p><p>https://i.ibb.co/VT9MtYH/sample-embeddings.png</p>

---

 <a href='https://app.reviewnb.com/huggingface/notebooks/pull/270/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sayakpaul** [comment]
@abidlabs @freddyaboulton a gentle reminder regarding: https://github.com/huggingface/notebooks/pull/270#issuecomment-1321503361

**Comment by freddyaboulton** [comment]
Hi @sayakpau - thank you for the reminderl ! How can I help with the gradio demo?

**Comment by osanseviero** [comment]
Yes, they were just examples for inspiration. For a search example you can see https://huggingface.co/spaces/vivien/clip (yes, the input is text, not an image - also it's in streamlit). If you want Gradio, the main component to use is `gr.Gallery` as @freddyaboulton suggested. 

Btw I would suggest to check the left navbar at https://gradio.app/docs/ to get familiar with the available Gradio components to get ideas of what is possible without having to hack around. There aren't too many components and they can enable very cool use cases.

Kudos @freddyaboulton for the super nice example! 🔥

**Comment by sayakpaul** [comment]
<p>I couldn't come up with something salient. If you have ideas feel free to let me know. </p>

---

 <a href='https://app.reviewnb.com/huggingface/notebooks/pull/270/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sayakpaul** [comment]
<p>Usually, we first resize to a bigger size and then take. central crop. Here, <code>int((256 / 224) * extractor.size)</code> is calculating that bigger size to resize to.   </p>

---

 <a href='https://app.reviewnb.com/huggingface/notebooks/pull/270/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sayakpaul** [comment]
<p>To allow users test multiple models sharing the same preprocessing function (which is kinda same of these vision backbones). </p>

---

 <a href='https://app.reviewnb.com/huggingface/notebooks/pull/270/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sayakpaul** [comment]
<p>Yes, this will be updated. I am currently working on a parallel notebook that incorporates the FAISS utilities of <code>datasets</code>.  Thanks for the reminder. </p>

---

 <a href='https://app.reviewnb.com/huggingface/notebooks/pull/270/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sayakpaul** [comment]
@osanseviero @nateraw a gentle ping 🏓

**Comment by nateraw** [comment]
<p>That image is good!</p><p> </p><p>Also here - the link under "this resource could be helpful" at the end of the cell is broken (leads to a page with no content).</p>

---

 <a href='https://app.reviewnb.com/huggingface/notebooks/pull/270/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by osanseviero — APPROVED** [review]
Very cool! Let's make this go :fire: :rocket: when merged!

Happy for this to be merged once Nate's comments are resolved

**Comment by sayakpaul** [comment]
<p>Just fixed the link. It had a full-stop at the end. </p>

---

 <a href='https://app.reviewnb.com/huggingface/notebooks/pull/270/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
