### PR TITLE
Add loading_adapters.ipynb

### LINKED ISSUE #520: Fix broken link for diffusers/loading_adapters
while reading doc [Load adapters](https://huggingface.co/docs/diffusers/using-diffusers/loading_adapters)

I tried to open in Colab to run an example on this page.

open_colab

It will get Notebook not found on a new page.

It can't find loading_adapters.ipynb in [huggingface/notebooks](https://github.com/huggingface/notebooks)

### PR DESCRIPTION
**Pull request by thliang01**
add jupyter notebook for broken link

# What does this PR do?

Fixes #520 

## Who can review?

Feel free to tag members/contributors who may be interested in your PR.

@sayakpaul

### CODE REVIEW

**Comment by SahilCarterr** [comment]
I think you should also add notebook [here](https://github.com/huggingface/notebooks/tree/main/diffusers_doc/en/tensorflow) and [here](https://github.com/huggingface/notebooks/tree/main/diffusers_doc/en/pytorch).
@thliang01

**Comment by stevhliu** [comment]
Thanks for manually adding! Feel free to ping me for a review once you've also added the notebooks to the PyTorch and TensorFlow folders 🙂

**Comment by thliang01** [comment]
@stevhliu

I added the notebooks to the PyTorch and TensorFlow folders.

Please feel free to take a look at the notebook.

**Comment by thliang01** [comment]
@stevhliu

I have another question: Is **sayakpaul/EasyNegative-test** in Textual inversion empty?
The [sayakpaul/EasyNegative-test](https://huggingface.co/sayakpaul/EasyNegative-test) embeddings can't find in huggingface.
Is there any alternative for this?

**Review by stevhliu — APPROVED** [review]
Thanks for also adding the PyTorch/TensorFlow options! You can replace the EasyNegative embeddings with this one [here](https://huggingface.co/EvilEngine/easynegative) I think

**Review by stevhliu — APPROVED** [review]
Thanks again! 🤗

**Pull request merged**
